name: GildorymTrees
author: Hohahihehu
version: 0.0.1
main: com.gildorymrp.gildorymtrees.GildorymTreeGenerator
commands:
    savetree:
        description: Allows a player to save an in-game tree for use in growth events
        usage: /<command> [group] [rarity]
    treegroups:
        description: Generates a list of valid tree groups and rarities
        usage: /<command>